version: '3'

services:
  resa_keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    env_file:
      - .env
    container_name: resa_keycloack
    environment:
      KC_PROXY_HEADERS: forwarded

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://resa_keycloak_db:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: debug
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    depends_on:
      - resa_keycloak_db
    ports:
      - ${KC_PORT}:8080
    networks:
      - resa-network

  resa_keycloak_db:
    image: postgres:15
    env_file:
      - .env
    container_name: resa_keycloack_db
    volumes:
      - ./data/kc_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    hostname: resa_keycloak_db
    networks:
      - resa-network

  resa_front:
    build:
      context: front
    env_file:
      - .env
    container_name: resa_front
    restart: always
    depends_on:
      - resa_backend
    ports:
      - ${APP_PORT}:80
    networks:
      - resa-network

  resa_backend:
    build:
      context: back
    env_file:
      - .env
    container_name: resa_backend
    restart: always
    ports:
      - ${BACK_PORT}:80
    networks:
      - resa-network

  # resa_soap:
  #   build:
  #     context: soap
  #   env_file:
  #     - .env
  #   container_name: resa_soap
  #   restart: always
  #   ports:
  #     - ${SOAP_PORT}:80
  #   networks:
  #     - resa-network

networks:
  resa-network:
    name: resa-network
    driver: bridge