# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import main_pb2 as main__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in main_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class HotelReservationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveHotel = channel.unary_unary(
                '/reservation.HotelReservation/ReserveHotel',
                request_serializer=main__pb2.HotelRequest.SerializeToString,
                response_deserializer=main__pb2.HotelResponse.FromString,
                _registered_method=True)
        self.ListReservedHotels = channel.unary_unary(
                '/reservation.HotelReservation/ListReservedHotels',
                request_serializer=main__pb2.ListHotelsRequest.SerializeToString,
                response_deserializer=main__pb2.ListHotelsResponse.FromString,
                _registered_method=True)


class HotelReservationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReserveHotel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReservedHotels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelReservationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveHotel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveHotel,
                    request_deserializer=main__pb2.HotelRequest.FromString,
                    response_serializer=main__pb2.HotelResponse.SerializeToString,
            ),
            'ListReservedHotels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReservedHotels,
                    request_deserializer=main__pb2.ListHotelsRequest.FromString,
                    response_serializer=main__pb2.ListHotelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reservation.HotelReservation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reservation.HotelReservation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotelReservation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReserveHotel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservation.HotelReservation/ReserveHotel',
            main__pb2.HotelRequest.SerializeToString,
            main__pb2.HotelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReservedHotels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservation.HotelReservation/ListReservedHotels',
            main__pb2.ListHotelsRequest.SerializeToString,
            main__pb2.ListHotelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FlightReservationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveFlight = channel.unary_unary(
                '/reservation.FlightReservation/ReserveFlight',
                request_serializer=main__pb2.FlightRequest.SerializeToString,
                response_deserializer=main__pb2.FlightResponse.FromString,
                _registered_method=True)
        self.ListReservedFlights = channel.unary_unary(
                '/reservation.FlightReservation/ListReservedFlights',
                request_serializer=main__pb2.ListFlightsRequest.SerializeToString,
                response_deserializer=main__pb2.ListFlightsResponse.FromString,
                _registered_method=True)


class FlightReservationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReserveFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReservedFlights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightReservationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveFlight': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveFlight,
                    request_deserializer=main__pb2.FlightRequest.FromString,
                    response_serializer=main__pb2.FlightResponse.SerializeToString,
            ),
            'ListReservedFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReservedFlights,
                    request_deserializer=main__pb2.ListFlightsRequest.FromString,
                    response_serializer=main__pb2.ListFlightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reservation.FlightReservation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reservation.FlightReservation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlightReservation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReserveFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservation.FlightReservation/ReserveFlight',
            main__pb2.FlightRequest.SerializeToString,
            main__pb2.FlightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReservedFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservation.FlightReservation/ListReservedFlights',
            main__pb2.ListFlightsRequest.SerializeToString,
            main__pb2.ListFlightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
